language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4snapshot"
  - nightly

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
